import * as v from "valibot";

/**
 * FlueInsightSchema
 *
 * A single insight generated by the Flue LLM enhancement layer.
 * In MS1 (shell), this schema exists but is not populated by any
 * data path. Real LLM workflow is implemented in MS2.
 */
export const FlueInsightSchema = v.object({
  findingId: v.string(),
  insight: v.string(),
});
export type FlueInsight = v.InferOutput<typeof FlueInsightSchema>;

/**
 * FlueResponseSchema
 *
 * The expected structured JSON response from the Flue LLM when asked
 * to generate insights for diagnostic findings.
 *
 * The response must contain a "findings" array with objects that have
 * a "findingId" (matching a finding ID sent to Flue) and an "insight"
 * string containing the AI-generated analysis text.
 *
 * This schema is used by the MS2 FlueWorkflowRunner to Valibot-validate
 * the Flue response before populating flueInsights.
 */
export const FlueResponseSchema = v.object({
  findings: v.array(
    v.object({
      findingId: v.string(),
      insight: v.string(),
    }),
  ),
});
export type FlueResponse = v.InferOutput<typeof FlueResponseSchema>;

/**
 * FlueInsightsSectionSchema
 *
 * The optional flueInsights section on DoctorReport. Always marked
 * as experimental. When Flue is enabled and available, this section
 * contains zero or more insights and optional warnings.
 *
 * - enabled: true when --flue was passed and Flue runtime loaded
 * - experimental: always true (literal)
 * - generatedAt: ISO timestamp when Flue insights were generated
 * - insights: array of FlueInsight objects (populated in MS2)
 * - warnings: array of warning strings (e.g., "Flue unavailable")
 */
export const FlueInsightsSectionSchema = v.object({
  enabled: v.boolean(),
  experimental: v.literal(true),
  generatedAt: v.optional(v.string()),
  insights: v.array(FlueInsightSchema),
  warnings: v.array(v.string()),
});
export type FlueInsightsSection = v.InferOutput<typeof FlueInsightsSectionSchema>;
